spring.application.name=ecommerce-backend
spring.datasource.url=jdbc:h2:mem:ecomdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
ecommerce.app.jwtSecret=SecretKey03845093845093845093845093845093845093845093845093845093845093845
ecommerce.app.jwtExpirationMs=86400000

# Stripe Configuration
stripe.api.key=sk_test_4eC39HqLyjWDarjtT1zdp7dc
